export const launchpadLensAbi = [
  {
    type: 'function',
    name: 'getAuctionState',
    inputs: [{name: 'auction', type: 'address', internalType: 'address'}],
    outputs: [
      {
        name: 'state',
        type: 'tuple',
        internalType: 'struct LaunchpadLens.AuctionState',
        components: [
          {name: 'clearingPriceQ96', type: 'uint256', internalType: 'uint256'},
          {name: 'currencyRaised', type: 'uint256', internalType: 'uint256'},
          {name: 'totalBidAmount', type: 'uint256', internalType: 'uint256'},
          {name: 'totalCleared', type: 'uint256', internalType: 'uint256'},
          {name: 'startBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'endBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'claimBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'floorPriceQ96', type: 'uint256', internalType: 'uint256'},
          {name: 'tickSpacingQ96', type: 'uint256', internalType: 'uint256'},
          {name: 'token', type: 'address', internalType: 'address'},
          {name: 'currency', type: 'address', internalType: 'address'},
          {name: 'totalSupply', type: 'uint128', internalType: 'uint128'},
          {name: 'tokenDecimals', type: 'uint8', internalType: 'uint8'},
          {name: 'currencyDecimals', type: 'uint8', internalType: 'uint8'},
          {name: 'status', type: 'uint8', internalType: 'uint8'},
          {name: 'progress', type: 'uint8', internalType: 'uint8'},
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAuctionStateAndTokenData',
    inputs: [{name: 'auction', type: 'address', internalType: 'address'}],
    outputs: [
      {
        name: 'auctionState',
        type: 'tuple',
        internalType: 'struct LaunchpadLens.AuctionState',
        components: [
          {name: 'clearingPriceQ96', type: 'uint256', internalType: 'uint256'},
          {name: 'currencyRaised', type: 'uint256', internalType: 'uint256'},
          {name: 'totalBidAmount', type: 'uint256', internalType: 'uint256'},
          {name: 'totalCleared', type: 'uint256', internalType: 'uint256'},
          {name: 'startBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'endBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'claimBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'floorPriceQ96', type: 'uint256', internalType: 'uint256'},
          {name: 'tickSpacingQ96', type: 'uint256', internalType: 'uint256'},
          {name: 'token', type: 'address', internalType: 'address'},
          {name: 'currency', type: 'address', internalType: 'address'},
          {name: 'totalSupply', type: 'uint128', internalType: 'uint128'},
          {name: 'tokenDecimals', type: 'uint8', internalType: 'uint8'},
          {name: 'currencyDecimals', type: 'uint8', internalType: 'uint8'},
          {name: 'status', type: 'uint8', internalType: 'uint8'},
          {name: 'progress', type: 'uint8', internalType: 'uint8'},
        ],
      },
      {
        name: 'tokenData',
        type: 'tuple',
        internalType: 'struct LaunchpadLens.TokenData',
        components: [
          {name: 'name', type: 'string', internalType: 'string'},
          {name: 'symbol', type: 'string', internalType: 'string'},
          {name: 'decimals', type: 'uint8', internalType: 'uint8'},
          {name: 'totalSupply', type: 'uint256', internalType: 'uint256'},
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBids',
    inputs: [
      {name: 'auction', type: 'address', internalType: 'address'},
      {name: 'bidIds', type: 'uint256[]', internalType: 'uint256[]'},
    ],
    outputs: [
      {
        name: 'bids',
        type: 'tuple[]',
        internalType: 'struct LaunchpadLens.BidWithId[]',
        components: [
          {name: 'id', type: 'uint256', internalType: 'uint256'},
          {name: 'startBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'startCumulativeMps', type: 'uint24', internalType: 'uint24'},
          {name: 'exitedBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'maxPrice', type: 'uint256', internalType: 'uint256'},
          {name: 'owner', type: 'address', internalType: 'address'},
          {name: 'amountQ96', type: 'uint256', internalType: 'uint256'},
          {name: 'tokensFilled', type: 'uint256', internalType: 'uint256'},
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getMultipleAuctionStates',
    inputs: [{name: 'auctions', type: 'address[]', internalType: 'address[]'}],
    outputs: [
      {
        name: 'states',
        type: 'tuple[]',
        internalType: 'struct LaunchpadLens.AuctionState[]',
        components: [
          {name: 'clearingPriceQ96', type: 'uint256', internalType: 'uint256'},
          {name: 'currencyRaised', type: 'uint256', internalType: 'uint256'},
          {name: 'totalBidAmount', type: 'uint256', internalType: 'uint256'},
          {name: 'totalCleared', type: 'uint256', internalType: 'uint256'},
          {name: 'startBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'endBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'claimBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'floorPriceQ96', type: 'uint256', internalType: 'uint256'},
          {name: 'tickSpacingQ96', type: 'uint256', internalType: 'uint256'},
          {name: 'token', type: 'address', internalType: 'address'},
          {name: 'currency', type: 'address', internalType: 'address'},
          {name: 'totalSupply', type: 'uint128', internalType: 'uint128'},
          {name: 'tokenDecimals', type: 'uint8', internalType: 'uint8'},
          {name: 'currencyDecimals', type: 'uint8', internalType: 'uint8'},
          {name: 'status', type: 'uint8', internalType: 'uint8'},
          {name: 'progress', type: 'uint8', internalType: 'uint8'},
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getMultipleTokenData',
    inputs: [{name: 'tokens', type: 'address[]', internalType: 'address[]'}],
    outputs: [
      {
        name: 'data',
        type: 'tuple[]',
        internalType: 'struct LaunchpadLens.TokenData[]',
        components: [
          {name: 'name', type: 'string', internalType: 'string'},
          {name: 'symbol', type: 'string', internalType: 'string'},
          {name: 'decimals', type: 'uint8', internalType: 'uint8'},
          {name: 'totalSupply', type: 'uint256', internalType: 'uint256'},
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getTokenData',
    inputs: [{name: 'token', type: 'address', internalType: 'address'}],
    outputs: [
      {
        name: 'data',
        type: 'tuple',
        internalType: 'struct LaunchpadLens.TokenData',
        components: [
          {name: 'name', type: 'string', internalType: 'string'},
          {name: 'symbol', type: 'string', internalType: 'string'},
          {name: 'decimals', type: 'uint8', internalType: 'uint8'},
          {name: 'totalSupply', type: 'uint256', internalType: 'uint256'},
        ],
      },
    ],
    stateMutability: 'view',
  },
] as const;
